version: '3.9'
services:
  amongUS_bot:
    # container_name: ggd_bot
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - MONGO_HOST=ggd_bot_db
    restart: always
    networks:
      - botnet

networks:
  botnet:
    name: botnet
    driver: bridge